[package]
name = "whois"
version = "0.1.0"
authors = ["p <p@supr.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
rustyline = "5.0.4"
num_cpus = "1.0"
